# Generated by Django 2.2.24 on 2021-06-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmsToWatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Original_name', models.CharField(max_length=200)),
                ('Year', models.DateTimeField()),
                ('Sinopsis', models.TextField()),
                ('Director', models.CharField(max_length=30)),
                ('Duration', models.CharField(max_length=6)),
                ('Genres', models.CharField(max_length=200)),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
