# Generated by Django 2.2.24 on 2021-07-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20210630_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmstowatch',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
